name: Maven build

on:
  push:
    branches:
    - legacy
  pull_request:
    branches:
    - legacy

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: BetterMelon
        path: target/BetterMelon.jar
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v1.2.1
      if: success()
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "dev-legacy"
        prerelease: false
        title: "BetterMelon-legacy 自动构建版本"
        files: |
          target/BetterMelon.jar
        
